name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install

    - name: Deploy to Hostinger
      env:
        HOSTINGER_API_TOKEN: ${{ secrets.HOSTINGER_API_TOKEN }}
      run: |
        zip -r build.zip . -x ".git/*"
        curl -X POST "https://api.hostinger.com/v1/sites/deploy" \
        -H "Authorization: Bearer $HOSTINGER_API_TOKEN" \
        -F "file=@$(pwd)/build.zip" \
        -F "destination=/public_html"